services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      LETSENCRYPT_HOST: mongo.ccw.diveinai.pl
      VIRTUAL_HOST: mongo.ccw.diveinai.pl
      VIRTUAL_PORT: 27017
    ports:
      - 27017:27017
    volumes:
      - ./.mongo-data:/data/db
    networks:
      - net


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  net:
    external: true